### ISSUE TITLE
New Log file locations for version 11.6.0 and Later

### ISSUE THREAD

**Issue by jaw4uz** [munkireport/crashplan#10]
The Crashplan.py is failing on all computers running version 11.6.0 or later of Crashplan due to the log files being in a new location. https://support.crashplan.com/hc/en-us/articles/8959806429325-Read-CrashPlan-app-log-files

Munkireport logs from a computer running version 11.7.0 of crashplan
Oct 21 2025 08:09:07 -0400 Running crashplan.py
Oct 21 2025 08:09:07 -0400 CrashPlan log not found at: /Library/Logs/CrashPlan/history.log or /Library/Logs/CrashPlan/history.log.0

**Comment by tuxudo** [comment]
This should be fixed with v4.1 of the crashplan module. Please test if you can, I do not have a Crashplan instance to test with.

**Comment by jaw4uz** [comment]
It's still not working it looks like in the crashplan.py on line 26 there is a == instead of just =

**Comment by tuxudo** [comment]
Thank you for the bug report. The script has been fixed and a new version released. Please test and let me know if it is now working properly.
